---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: whisper
          image: vonsovsky/whisper-api:v0.1.0
          ports:
            - containerPort: 8080
