apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper-api
  labels:
    app.kubernetes.io/name: whisper-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: whisper
      app.kubernetes.io/name: whisper-api
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: whisper
        app.kubernetes.io/name: whisper-api
    spec:
      containers:
        - name: whisper-api-1
          image: vonsovsky/whisper-api:v0.1.3-tiny
          imagePullPolicy: Always
          resources:
            limits:
              nvidia.com/gpu: 1
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
